### ISSUE TITLE
[Suggestion] Event Types.

### ISSUE THREAD

**Issue by Root3287** [Submanifold/Events#1]
Hello,
I've noticed that you posted a blog on a simple event system over [here](https://bastian.rieck.ru/blog/posts/2015/event_system_cxx11/). One of the limitations that you put is, "Another issue is a systematic problem: I cannot guarantee the uniqueness of the self-described events. If a client chooses to implements events A and B and both return, say "Foo" as their event type, the dispatcher will not be able to separate between these events." 

A solution to this issue is to make the `Dispatcher` and `Event` into a classes template. Then we can make a struct that defines different types. For example.

```c++
// Defines the different event types for A
enum class EventTypeA{
e1, e2, e3, e4
};

// Defines different event types for B
enum class EventTypeB{
e1, e2, e3, e4
};

Dispatcher<EventTypeA> _dispatcherA;
Dispatcher<EventTypeB> _dispatcherB;

_dispatcherA.subscribe(EventTypeA::e1, [](const Event<EventTypeA>& event){
    // Received for type e1 for Event A.  Process what you want here.
});
_dispatcherB.subscribe(EventTypeB::e1, [](const Event<EventTypeB>& event){
    // Received for type e1 for Event B.  Process what you want here.
});
```

To implement this you need to change event to:
```c++
template<typename T>
class Event
{
public:
  virtual~ Event();

  virtual T type() const = 0;
};
```

Then in the EventDispatcher
```c++
template<typename T>
class Dispatcher
{
public:

  using SlotType = std::function< void( const Event<T>& ) >;

  void subscribe( const T& descriptor, SlotType&& slot );

  void post( const Event<T>& event ) const;

private:

 std::map< Event::DescriptorType, std::vector<SlotType> > _observers;
};

```

**Comment by HerrDingenz** [comment]
I like that idea!

**Comment by Pseudomanifold** [comment]
I like it too—but I am currently lacking the time to integrate this. Feel free to open a pull request for this, I'll gladly integrate it later. In the meantime, I will link to the issue in the blog post.

**Comment by Pseudomanifold** [comment]
Thanks a lot for your work—just updated and rebased everything.
