### ISSUE TITLE
Any idea how to unsubscribe a handling function?

### ISSUE THREAD

**Issue by inlet511** [Submanifold/Events#4]
When I am Implementing a similar system, I found that if I use std::bind to create some std::function, I can't compare the addresses of these std::functions. So I can't implement a method like  removeEvent("SomeEventName", bind(.........))

**Comment by Pseudomanifold** [comment]
I used an ID for this purpose in a previous version of the code. Check this version out: https://github.com/Pseudomanifold/Events/tree/c2c8b143a616656fc4628939a9aab89b1019dfa2
